language: elixir
elixir:
  - '1.8.0'
  - '1.7.0'
services: 
  - postgresql
before_script:
  - psql -c 'create database access_pass_test;' -U postgres
addons:
  postgresql: "10"
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres